####

POST http://127.0.0.1:5000/Register

content-type: application/json

{
    "username": Phelim,
    "pasword": Password
}

#####
POST http://127.0.0.1:5000/notes

content-type: application/json

{
    "title": Phelim,
    "note": Password
}